version: 2.1
jobs:
    build:
      docker:
        - image: awsdeeplearningteam/mms-build:python3.6@sha256:2c1afa8834907ceec641d254dffbf4bcc659ca2d00fd6f2872d7521f32c9fa2e
#        - image: circleci/python:3.6.5
      steps:
        - checkout
#        - run: frontend/gradlew -p frontend clean fJ build --no-daemon --max-workers 2
        - run:
            command: |
              pip install psutil
              pip install future
              pip install Pillow
              pip install wheel
              pip install twine
              pip install requests
              pip install mock
              pip install numpy
              pip install Image
              pip install mxnet==1.5.0
              pip install pytest==4.0.0
              pip install pytest-mock
              pip install pytest-cov
        - run:
            command: |
              export _JAVA_OPTIONS="-Xmx2048m"
              pip install .
        - run: python -m pytest --cov-report html:htmlcov --cov=mms/ mms/tests/unit_tests/
        - store_artifacts:
            path: htmlcov
