version: 2.1
jobs:
    build_frontend:
      docker:
        - image: prashantsail/mms-build:latest
      steps:
        - checkout
        - run:
            name: Build frontend
            command: |
              ./frontend/gradlew -p frontend clean fJ assemble
              mkdir -p mms/frontend
              cp frontend/server/build/libs/server-1.0.jar mms/frontend/model-server.jar
        - run: rm -rf .git  # Remove repository info to save size
        - persist_to_workspace:
            root: .
            paths:
              - .

    gradle_testng:
      docker:
        - image: prashantsail/mms-build:latest
      steps:
        - attach_workspace:
            at: .
        - run:
            name: Execute gradle testng
            command: |
              export _JAVA_OPTIONS="-Xmx1024m"
              ./frontend/gradlew -p frontend clean fJ test
        - store_artifacts:
            name: Store gradle testng results
            path: frontend/server/build/reports/tests/test
            destination: frontend-results

    python_unit_tests:
      docker:
        - image: prashantsail/mms-build:latest
      steps:
        - attach_workspace:
            at: .
        - run:
            name: Execute python unit tests
            command: |
              python -m pytest --cov-report html:htmlcov --cov=mms/ mms/tests/unit_tests/
        - store_artifacts:
            name: Store python Test results
            path: htmlcov
            destination: pytest-results

    api_tests:
      docker:
        - image: prashantsail/mms-build:latest
      steps:
        - attach_workspace:
            at: .
        - run:
            name: Install MMS
            command: |
              pip install .
        - run:
            name: Setup directories
            command: |
              mkdir test/report
              mkdir test/model_store
        - run:
            name: Execute Management API Tests
            command: |
              export _JAVA_OPTIONS="-Xmx1024m"
              multi-model-server --start --model-store test/model_store >> mms_management.log 2>&1
              sleep 10
              newman run -e test/postman/environment.json --verbose test/postman/management_api_test_collection.json -r cli,html --reporter-html-export test/report/management_report.html
              multi-model-server --stop
        - store_artifacts:
            name: Store server logs from management API tests
            path: mms_management.log
            destination: mms_management
        - store_artifacts:
            name: Store management API test results
            path: test/report
            destination: management-api-results

        - run:
            name: Execute Inference API Tests
            command: |
              export _JAVA_OPTIONS="-Xmx1024m"
              multi-model-server --start --model-store test/model_store >> mms_inference.log 2>&1
              sleep 10
              newman run -e test/postman/environment.json --verbose test/postman/inference_api_test_collection.json -d test/postman/inference_data.json -r cli,html --reporter-html-export test/report/inference_report.html
              multi-model-server --stop
        - store_artifacts:
            name: Store server logs from inference API tests
            path: mms_inference.log
            destination: mms_inference
        - store_artifacts:
            name: Store inference API test results
            path: test/report
            destination: inference-api-results

        - run:
            name: Execute https API Tests
            command: |
              export _JAVA_OPTIONS="-Xmx1024m"
              multi-model-server --start --mms-config test/resources/config.properties --model-store test/model_store >> mms_https.log 2>&1
              sleep 10
              newman run -e test/postman/environment.json --verbose test/postman/https_test_collection.json -r cli,html --reporter-html-export test/report/https_report.html
              multi-model-server --stop
        - store_artifacts:
            name: Store server logs from https API tests
            path: mms_https.log
            destination: mms_https
        - store_artifacts:
            name: Store https API test results
            path: test/report
            destination: https-api-results

    benchmark:
      docker:
        - image: prashantsail/mms-build:latest
      steps:
        - attach_workspace:
            at: .
        - run:
            name: Install MMS
            command: |
              pip install .
        - run:
            name: Start server, Execute benchmark tests
            command: |
              mkdir -p /home/ubuntu/.linuxbrew/Cellar/jmeter/5.3/libexec/bin/
              ln -s /opt/apache-jmeter-5.3/bin/jmeter /home/ubuntu/.linuxbrew/Cellar/jmeter/5.3/libexec/bin/jmeter
              export _JAVA_OPTIONS="-Xmx1024m"
              multi-model-server --start
              sleep 30
              cd benchmarks
              python benchmark.py latency
              multi-model-server --stop
        - store_artifacts:
            name: Store Benchmark Latency resnet-18 results
            path: /tmp/MMSBenchmark/out/latency/resnet-18/report/
            destination: benchmark-latency-resnet-18

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_frontend
      - gradle_testng:
          requires:
            - build_frontend
      - python_unit_tests:
          requires:
            - build_frontend
      - api_tests:
          requires:
            - build_frontend
      - benchmark:
          requires:
            - build_frontend