version: 2.1
jobs:
    build:
      docker:
        - image awsdeeplearningteam/mxnet-model-server:latest
#        - image:  awsdeeplearningteam/multi-model-server:latest
#        - image: circleci/python:3.6
      steps:
        - checkout
        - run: frontend/gradlew -p frontend clean build
#        - run: pip install .
#        - run: python --version
#        - run: java -version