version: 2.1
jobs:
    myjob1:
      docker:
        - image: awsdeeplearningteam/mms-build:python3.6@sha256:2c1afa8834907ceec641d254dffbf4bcc659ca2d00fd6f2872d7521f32c9fa2e
      steps:
        - run: pip install pandas
    myjob2:
      docker:
        - image: awsdeeplearningteam/mms-build:python3.6@sha256:2c1afa8834907ceec641d254dffbf4bcc659ca2d00fd6f2872d7521f32c9fa2e
      steps:
        - run: pip show pandas

workflows:
  version: 2
  build_and_test:
    jobs:
      - myjob1
      - myjob2