version: 2.1
jobs:
    build:
      docker:
        - image: awsdeeplearningteam/mms-build:python3.6@sha256:2c1afa8834907ceec641d254dffbf4bcc659ca2d00fd6f2872d7521f32c9fa2e
#        - image: circleci/python:3.6.5
      steps:
        - checkout
        - run:
            command: |
              pip install psutil
              pip install future
              pip install Pillow
              pip install wheel
              pip install twine
              pip install requests
              pip install mock
              pip install numpy
              pip install Image
              pip install mxnet==1.5.0
              pip install pytest==4.0.0
              pip install pytest-mock
              pip install pytest-cov
#        - run:
#            command: |
#              export _JAVA_OPTIONS="-Xmx1024m"
#              frontend/gradlew -p frontend clean fJ build --no-daemon --max-workers 2
        - run:
            command: |
              export _JAVA_OPTIONS="-Xmx1024m"
              pip install .
        - store_artifacts:
            path: frontend/server/build/reports/tests/test
            destination: frontend-results

        - run: python -m pytest --cov-report html:htmlcov --cov=mms/ mms/tests/unit_tests/
        - store_artifacts:
            path: htmlcov
            destination: pytest-results

###############
        - run:
            command: |
              curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
              sudo apt-get install -y nodejs
              sudo npm install -g newman newman-reporter-html
              mkdir test/report
              mkdir test/model_store

        - run:
            command: |
              cd docker
              pwd
              multi-model-server --start >>ps.log 2>&1
              sleep 30
              curl -v -X POST "http://localhost:8081/models?initial_workers=1&synchronous=true&url=https%3A%2F%2Fs3.amazonaws.com%2Fmodel-server%2Fmodel_archive_1.0%2Fsqueezenet_v1.1.mar"
              curl http://localhost:8081/models
        - run:
            command: |
              curl -O https://s3.amazonaws.com/model-server/inputs/kitten.jpg
              curl -X POST http://localhost:8080/predictions/squeezenet_v1.1 -T kitten.jpg
        - store_artifacts:
            path: docker/ps.log
            destination: mmslog