version: 2.1
jobs:
    build:
      docker:
        - image: circleci/openjdk:8u252
        - image: circleci/python:3.6
      steps:
        - checkout
        - run: pip install .
#        - run: python --version
#        - run: java -version