version: 2.1
jobs:
    build:
      docker:
        - image: awsdeeplearningteam/mms-build:python3.6@sha256:2c1afa8834907ceec641d254dffbf4bcc659ca2d00fd6f2872d7521f32c9fa2e
#        - image: circleci/python:3.6.5
      steps:
        - checkout
        - run:
            command: |
              pip install psutil
              pip install future
              pip install Pillow
              pip install wheel
              pip install twine
              pip install requests
              pip install mock
              pip install numpy
              pip install Image
              pip install mxnet==1.5.0
              pip install pytest==4.0.0
              pip install pytest-mock
              pip install pytest-cov
#        - run:
#            command: |
#              export _JAVA_OPTIONS="-Xmx1024m"
#              frontend/gradlew -p frontend clean fJ build --no-daemon --max-workers 2
        - run:
            command: |
              export _JAVA_OPTIONS="-Xmx1024m"
              pip install .
        - store_artifacts:
            path: frontend/server/build/reports/tests/test
            destination: frontend-results

        - run: python -m pytest --cov-report html:htmlcov --cov=mms/ mms/tests/unit_tests/
        - store_artifacts:
            path: htmlcov
            destination: pytest-results

        - run: sudo apt-get -y install nodejs npm
        - run: sudo npm install -g newman newman-reporter-html
        - run:
            command:|
              mkdir test/report
              mkdri test/model_store
        - run: multi-model-server --start --model-store test/model_store
        - run:
            command: |
              newman run -e test/postman/environment.json --bail --verbose test/postman/management_api_test_collection.json -r cli,html --reporter-html-export test/report/management_report.html