version: 2.1
jobs:
    build:
      docker:
        - image: awsdeeplearningteam/mms-build:python3.6@sha256:2c1afa8834907ceec641d254dffbf4bcc659ca2d00fd6f2872d7521f32c9fa2e
      steps:
        - checkout
#        - run:
#            command: |
#              pip install future
#              pip install Pillow
#              pip install pytest==4.0.0
#              pip install wheel
#              pip install twine
#              pip install pytest-mock
#              pip install requests
#              pip install mxnet==1.5.0
#              pip install psutil
#        - run: frontend/gradlew -p frontend clean fJ build --no-daemon --max-workers 2
#        - run:
#            command: |
#              export _JAVA_OPTIONS="-Xmx2048m"
#              pip install .

        - run: pip install pylint pytest-mock pytest-cov pytest mxnet==1.5.0 numpy
        - run: python -m pytest --cov-report html:htmlcov --cov=mms/ mms/tests/unit_tests/
